In [1]:
#telefon_fiyat_regresyon.ipynb
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [22]:
import pickle

In [2]:
veri = pd.read_csv("telefon_fiyatlari.csv")
veri

Telefon kodu  RAM Kapasitesi  Dahili hafiza    Ekran Tipi   Fiyat
0            T1               4            128  SUPER AMOLED  3300.0
1            T2               6            256        AMOLED  4400.0
2            T3               4            128        AMOLED  2700.0
3            T4               6            128           IPS  3600.0
4            T5               6             64           IPS  3200.0
5            T6               8            128  SUPER AMOLED  4100.0
6            T7               4             64        AMOLED  2400.0
7            T8               4             64  SUPER AMOLED  3000.0
8            T9               8            256           IPS  4200.0
9           T10               6            256           IPS     NaN
10          T11               8            128        AMOLED     NaN

In [ ]:
veri.replace(to_replace=["SUPER AMOLED","AMOLED","IPS"],value=[3,2,1],inplace=True)
veri

In [12]:
# sklearn için veri setleri genelde eğitim(train)X, eğitim(train)y ve x_test ve y_test kısmı olarak
# 4 parçaya ayrılır.
x_egitim=veri.iloc[0:9,1:4].values
y_egitim=veri.iloc[0:9,4].values.reshape(-1,1)
x_tahmin=veri.iloc[9:,1:4].values


array([[  6, 256,   1],
       [  8, 128,   2]])

In [13]:
lr=LinearRegression()
lr.fit(x_egitim,y_egitim)

LinearRegression()

In [16]:
lr.predict([[8,256,3]])

array([[4807.14285714]])

In [19]:
#f(x)=ax1+bx2+cx3+d
print(lr.coef_)
print(lr.intercept_)

[[251.78571429   4.85491071 171.42857143]]
[1035.71428571]


In [20]:
lr.score(x_egitim,y_egitim)

0.8806439674315323

In [26]:
#model lr_telefon.pkl adında bir dosyaya kaydedildi
with open("lr_telefon.pkl","wb") as file:
    pickle.dump(lr,file)

In [27]:
with open("lr_telefon.pkl","rb") as file:
    model=pickle.load(file)

In [29]:
model.predict([[4,128,2]])

array([[3007.14285714]])

In [31]:
model.predict(x_tahmin)

array([[3960.71428571],
       [4014.28571429]])

In [34]:
from joblib import dump,load

In [35]:
#joblib ile kaydedelim
dump(lr,"telefon_reg.joblib")

['telefon_reg.joblib']

In [36]:
modelj=load("telefon_reg.joblib")

In [37]:
modelj.predict(x_tahmin)

array([[3960.71428571],
       [4014.28571429]])